name: Deploy Web

on:
  workflow_dispatch:
  push:
    branches:  [ "develop" ]

jobs:
  build:
    name: Create Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Get dependencies
        run: flutter pub get

      - name: Start Web Release Build
        run: flutter build web --release

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v2
        with:
          name: web-release
          path: ./build/web

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Web Release
        uses: actions/download-artifact@v2
        with:
          name: web-release

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

steps:
  - uses: actions/checkout@v3
  - uses: subosito/flutter-action@v2
    with:
      channel: 'stable'
  - run: flutter pub get
  - run: flutter test
  - run: flutter build web
